[package]
name = "quick-alias"
version = "0.1.0"
authors = ["tyagig <grvtyagi22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16.0"
clap = "2.33.3"